server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format.sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

auth:
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-seconds: 3600


logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG